services:
  # Layanan 1: Database Metadata (TETAP)
  db:
    image: postgres:15
    container_name: aqi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mlflow_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - aqi-network

  # Layanan 2: MLflow Tracking Server (TETAP)
  mlflow-server:
    image: python:3.10-slim
    container_name: aqi_mlflow
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
      mlflow server --backend-store-uri postgresql://admin:password123@db:5432/mlflow_db --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - mlflow-data:/mlflow/artifacts
    networks:
      - aqi-network

  # Layanan 3: API Inferensi (DIUBAH UNTUK SCALING)
  api-service:
    image: aqi_inference_image # Memakai image yang di-build MLflow tadi
    # CATATAN: container_name dan ports DIHAPUS agar Docker bisa membuat banyak replika
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server
    networks:
      - aqi-network
    deploy:
      mode: replicated
      replicas: 3 # MENGAKTIFKAN 3 REPLIKA

  # Layanan 4: Load Balancer (BARU)
  load-balancer:
    image: nginx:latest
    container_name: aqi_load_balancer
    ports:
      - "8080:80" # Mengekspos port 8080 ke laptop kita
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
    networks:
      - aqi-network

networks:
  aqi-network:
    driver: bridge

volumes:
  pg-data:
  mlflow-data: