services:
  # Layanan 1: Database Metadata (TETAP)
  db:
    image: postgres:15
    container_name: aqi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mlflow_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - aqi-network

  # Layanan 2: MLflow Tracking Server (TETAP)
  mlflow-server:
    image: python:3.10-slim
    container_name: aqi_mlflow
    command: >
      bash -c "pip install mlflow==3.12.0 psycopg2-binary &&
      mlflow server --backend-store-uri postgresql://admin:password123@db:5432/mlflow_db --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --port 5000 --allowed-hosts '*'"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - mlflow-data:/mlflow/artifacts
    networks:
      - aqi-network

  # Layanan 3: API Inferensi Model XGBoost (Scaling)
  api-service:
    build: . # <-- GANTI tulisan "image:" menjadi "build: ."
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server
    networks:
      - aqi-network
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./mlruns:/app/mlruns  # 🚀 MANTRA SAKTI: Jembatani folder luar ke dalam Docker

  # Layanan 4: Load Balancer (BARU)
  load-balancer:
    image: nginx:latest
    container_name: aqi_load_balancer
    ports:
      - "8080:80" # Mengekspos port 8080 ke laptop kita
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
    networks:
      - aqi-network

  # Layanan 5: Prometheus (Pengumpul Metrik)
  prometheus:
    image: prom/prometheus:latest
    container_name: aqi_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - aqi-network
    depends_on:
      - load-balancer

  # Layanan 6: Grafana (Dashboard Visualisasi)
  grafana:
      image: grafana/grafana:latest
      container_name: aqi_grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      # 👇 TAMBAHKAN BARIS VOLUMES INI
      volumes:
        - grafana-storage:/var/lib/grafana
      networks:
        - aqi-network
      depends_on:
        - prometheus
    
networks:
  aqi-network:
    driver: bridge

volumes:
  pg-data:
  mlflow-data:
  grafana-storage: