events {}

http {
    upstream api_servers {
        # Mengarahkan trafik secara merata ke layanan bernama "api-service" pada port 8080
        server api-service:8080; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_servers;
        }
    }
}