name: Hourly Data Ingestion Pipeline

on:
  repository_dispatch:
    types: [trigger_hourly_ingest] # Nama event rahasia yang akan ditembak dari luar
  workflow_dispatch: # Memperbolehkan klik tombol 'Run workflow' manual dari web GitHub

# 👇 KUNCI SAKTI PENYELESAIAN ERROR 403 👇
permissions:
  contents: write # Mengizinkan robot melakukan commit dan push balik ke repositori

jobs:
  ingest-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pandas

      - name: Run Ingestion Script
        run: python src/data/automated_ingest.py

      - name: Auto Commit and Push New Data
        run: |
          git config --global user.name "Yoshia Automation Bot"
          git config --global user.email "yoshiabp-tif@users.noreply.github.com"
          git add -f data/interim/jakarta_aqi_cleaned.csv
          git commit -m "chore: automated hourly air quality data ingestion [skip ci]" || exit 0
          git push origin main